### PR TITLE
Add french translation

### PR DESCRIPTION
**Pull request by maxime-killinger**
Signed-off-by: Maxime Killinger <killin_m@MacBook-Pro-de-Maxime.local>

### CODE REVIEW

**Comment by maxime-killinger** [comment]
Feel free to PM me if you need any update on this translation in the future.

**Comment by johannes-schliephake** [comment]
That's so awesome, thanks for your translation! Makes me really happy.

I would like to add your name to the list of contributors, is that ok for you?

**Comment by maxime-killinger** [comment]
It's ok for me yes

**Comment by johannes-schliephake** [comment]
> Feel free to PM me if you need any update on this translation in the future.

Hey, I just realized it's not possible to PM someone on GitHub. I have a few updates regarding translations. Please contact me via [mail@cdslash.de](mailto:mail@cdslash.de). Thanks in advance!

**Pull request merged**
